---
title: Kanban Live
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Kanban Live Ltd
email: chris@kanbanlive.com
description: 'Kanban Live is a cloud-based, inventory management system which makes stock control more efficient and saves you money. It works with all types of storage system, but is ideally suited to the management of open bins, two bin systems and TwinBins.'
baseurl: ''
url: http://kanbanlive.com
author: kanbanlive
logo: "assets/img/logo.png"
exclude:
- README.md
- CNAME
- Gemfile.lock
- Gemfile
twitter:
  username: kanbanlive
github:
  username: kanbanlive
disqus_short_name: kanbanlive
disqus_show_comment_count: false
google_analytics_tracking_id: UA-32668005-1
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
feed:
  path: atom.xml
paginate: 5
paginate_path: "/blog/page:num/"
