title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

---
title: Kanban Live
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
name: Kanban Live Ltd
email: chris@kanbanlive.com
description: 'I help aerospace MRO''s and parts suppliers improve their operational
  efficiency with modern ERP and reporting software built on top of legacy systems

'
baseurl: ''
url: https://kanbanlive.com
author: kanbanlive
logo: "assets/img/logo.png"
exclude:
- README.md
- CNAME
- Gemfile.lock
- Gemfile
twitter:
  username: kanbanlive
github:
  username: kanbanlive
disqus_short_name: yellowfeather
disqus_show_comment_count: false
google_analytics_tracking_id: UA-32668005-1
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: "/blog/:title/"
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
feed:
  path: atom.xml
paginate: 4
paginate_path: "/blog/page:num/"
